cd C:\OPENGL

set RAPTOR_VERSION="2.16.3"
set PLATFORM_SDK=C:\Program Files\Microsoft SDKs\Windows\v7.0

set RAPTOR_ROOT=C:\OPENGL\Raptor
set PATH=%PATH%;%RAPTOR_ROOT%\Redist\bin

set WMSDK=C:\OPENGL\WMSDK\WMFSDK95

set FREETYPE_INCLUDE_PATH=%RAPTOR_ROOT%\AddOns\freetype-2.5.5\include
set FREETYPE_LIB_PATH=%RAPTOR_ROOT%\AddOns\freetype-2.5.5\lib
set FREETYPE_BIN_PATH=%RAPTOR_ROOT%\AddOns\freetype-2.5.5\bin

set ZLIB_INCLUDE_PATH=%RAPTOR_ROOT%\AddOns\zlib128\include
set ZLIB_LIB_PATH=%RAPTOR_ROOT%\AddOns\zlib128\lib\VC10
set ZLIB_BIN_PATH=%RAPTOR_ROOT%\AddOns\zlib128\bin\VC10

set XERCES_INCLUDE_PATH=%RAPTOR_ROOT%\AddOns\xercesc_3_1
set XERCES_LIB_PATH=%RAPTOR_ROOT%\AddOns\xercesc_3_1\VC10
set XERCES_BIN_PATH=%RAPTOR_ROOT%\AddOns\xercesc_3_1\VC10

set JPEGLIB_INCLUDE_PATH=%RAPTOR_ROOT%\AddOns\JpegLib\include
set JPEGLIB_LIB_PATH=%RAPTOR_ROOT%\AddOns\JpegLib\lib
set JPEGLIB_BIN_PATH=%RAPTOR_ROOT%\AddOns\JpegLib\lib

set TIFFLIB_INCLUDE_PATH=%RAPTOR_ROOT%\AddOns\TiffLib\include
set TIFFLIB_LIB_PATH=%RAPTOR_ROOT%\AddOns\TiffLib\lib\VC10
set TIFFLIB_BIN_PATH=%RAPTOR_ROOT%\AddOns\TiffLib\lib\VC10

set PNGLIB_INCLUDE_PATH=%RAPTOR_ROOT%\AddOns\libpng-1.6.16\include
set PNGLIB_LIB_PATH=%RAPTOR_ROOT%\AddOns\libpng-1.6.16\lib\VC10
set PNGLIB_BIN_PATH=%RAPTOR_ROOT%\AddOns\libpng-1.6.16\bin\VC10

set OPENEXRLIB_INCLUDE_PATH=%RAPTOR_ROOT%\AddOns\OpenEXRLib\include
set OPENEXRLIB_LIB_PATH=%RAPTOR_ROOT%\AddOns\OpenEXRLib\lib\vc10
set OPENEXRLIB_BIN_PATH=%RAPTOR_ROOT%\AddOns\OpenEXRLib\bin\vc10

SET OPENCL_INCLUDE_PATH=C:\Program Files (x86)\Intel\OpenCL SDK\3.0\include
SET OPENCL_LIB_PATH=C:\Program Files (x86)\Intel\OpenCL SDK\3.0\lib\x86
SET OPENCL_BIN_PATH=C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86

set VULKAN_INCLUDE_PATH=%RAPTOR_ROOT%\AddOns\vulkan\include
set VULKAN_BIN_PATH=c:\windows\system32

"C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\VCExpress.exe"

exit


