set RAPTOR_VERSION=2.17.0
set RAPTOR_RELEASE=2.17

set RAPTOR_ROOT=F:\VisualStudioProjects\Raptor
set PATH=%PATH%;%RAPTOR_ROOT%\Redist\bin


set FREETYPE_INCLUDE_PATH=%RAPTOR_ROOT%\AddOns\freetype-2.9.1\include
set FREETYPE_LIB_PATH=%RAPTOR_ROOT%\AddOns\freetype-2.9.1\lib\VC12
set FREETYPE_BIN_PATH=%RAPTOR_ROOT%\AddOns\freetype-2.9.1\bin\VC12

set ZLIB_INCLUDE_PATH=%RAPTOR_ROOT%\AddOns\zlib-1.2.11\include
set ZLIB_LIB_PATH=%RAPTOR_ROOT%\AddOns\zlib-1.2.11\lib\VC12
set ZLIB_BIN_PATH=%RAPTOR_ROOT%\AddOns\zlib-1.2.11\bin\VC12

set XERCES_INCLUDE_PATH=%RAPTOR_ROOT%\AddOns\xercesc-3.2.2\include
set XERCES_LIB_PATH=%RAPTOR_ROOT%\AddOns\xercesc-3.2.2\lib\VC12
set XERCES_BIN_PATH=%RAPTOR_ROOT%\AddOns\xercesc-3.2.2\bin\VC12

set JPEGLIB_INCLUDE_PATH=%RAPTOR_ROOT%\AddOns\JpegLib-v9\include
set JPEGLIB_LIB_PATH=%RAPTOR_ROOT%\AddOns\JpegLib-v9\lib\VC12
set JPEGLIB_BIN_PATH=%RAPTOR_ROOT%\AddOns\JpegLib-v9\lib\VC12

set TIFFLIB_INCLUDE_PATH=%RAPTOR_ROOT%\AddOns\TiffLib-4.0.10\include
set TIFFLIB_LIB_PATH=%RAPTOR_ROOT%\AddOns\TiffLib-4.0.10\lib\VC12
set TIFFLIB_BIN_PATH=%RAPTOR_ROOT%\AddOns\TiffLib-4.0.10\lib\VC12

set PNGLIB_INCLUDE_PATH=%RAPTOR_ROOT%\AddOns\libpng-1.6.36\include
set PNGLIB_LIB_PATH=%RAPTOR_ROOT%\AddOns\libpng-1.6.36\lib\VC12
set PNGLIB_BIN_PATH=%RAPTOR_ROOT%\AddOns\libpng-1.6.36\bin\VC12

set OPENEXRLIB_INCLUDE_PATH=%RAPTOR_ROOT%\AddOns\OpenEXR-2.3.0\include
set OPENEXRLIB_LIB_PATH=%RAPTOR_ROOT%\AddOns\OpenEXR-2.3.0\lib\VC12
set OPENEXRLIB_BIN_PATH=%RAPTOR_ROOT%\AddOns\OpenEXR-2.3.0\bin\VC12

set OPENCL_INCLUDE_PATH=E:\Intel\OpenCL\sdk\include
set OPENCL_LIB_PATH=E:\Intel\OpenCL\sdk\lib\x86
set OPENCL_BIN_PATH=E:\Intel\OpenCL\sdk\bin\x86

set VULKAN_INCLUDE_PATH=%RAPTOR_ROOT%\AddOns\vulkan\include
set VULKAN_BIN_PATH=c:\windows\system32

cd %RAPTOR_ROOT%

"E:\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe"


